// Phase 3: Advanced AI Engineering (relocated from Frontend to AI stream)
export const phase3AdvancedAI = {
  title: "Phase 3: Advanced AI Engineering",
  description: "Master fine-tuning, AI safety, multimodal models, and AI system design.",
  slug: "phase-3-advanced-ai",
  topics: [
    {
      title: "Fine-tuning & Model Customization",
      description: "Learn fine-tuning techniques: supervised fine-tuning, RLHF, LoRA, and QLoRA for customizing LLMs.",
      slug: "fine-tuning-models", difficulty: 4, prerequisites: [0, 1, 2],
      concepts: [
        { title: "Supervised Fine-Tuning (SFT)", description: "Fine-tune base models on instruction datasets. Dataset format: {instruction, input, output}. Training: cross-entropy loss on response tokens. Epochs: 1-3 typically. Learning rate: 1e-5 to 5e-5. Overfitting: monitor validation loss, use early stopping." },
        { title: "Parameter-Efficient Fine-Tuning", description: "LoRA: low-rank adaptation matrices added to attention weights. Rank: 8-64. Alpha: 16-128. QLoRA: 4-bit quantized base + LoRA. Reduces memory from 16× model size to 4×. Train on single GPU. Adapters: small trainable modules inserted between layers." },
        { title: "RLHF & Alignment", description: "Reinforcement Learning from Human Feedback. Step 1: collect preference pairs. Step 2: train reward model. Step 3: PPO fine-tuning. DPO: Direct Preference Optimization bypasses reward model. Constitutional AI: self-critique for alignment. RLHF improves helpfulness, honesty, harmlessness." },
      ],
      examples: [
        { title: "LoRA Fine-tuning with HuggingFace", description: "Fine-tune a model using LoRA with PEFT library", starterCode: "from transformers import AutoModelForCausalLM, AutoTokenizer, TrainingArguments\nfrom peft import LoraConfig, get_peft_model\nfrom datasets import Dataset\n\nmodel_name = \"microsoft/phi-2\"\n# Load model, configure LoRA, train", solutionCode: "from transformers import AutoModelForCausalLM, AutoTokenizer, TrainingArguments, Trainer\nfrom peft import LoraConfig, get_peft_model, TaskType\nfrom datasets import Dataset\nimport torch\n\nmodel_name = \"microsoft/phi-2\"\ntokenizer = AutoTokenizer.from_pretrained(model_name)\ntokenizer.pad_token = tokenizer.eos_token\n\nmodel = AutoModelForCausalLM.from_pretrained(model_name, torch_dtype=torch.float16, device_map=\"auto\")\n\nlora_config = LoraConfig(\n    task_type=TaskType.CAUSAL_LM,\n    r=16,\n    lora_alpha=32,\n    lora_dropout=0.05,\n    target_modules=[\"q_proj\", \"v_proj\"],\n)\n\nmodel = get_peft_model(model, lora_config)\nmodel.print_trainable_parameters()\n\ndata = [{\"text\": \"Instruction: Write a haiku about AI.\\nResponse: Silicon dreams wake\\nNeural pathways softly glow\\nMachine minds create.\"}]\ndataset = Dataset.from_list(data)\n\ndef tokenize(examples):\n    return tokenizer(examples[\"text\"], truncation=True, padding=\"max_length\", max_length=256)\n\ndataset = dataset.map(tokenize)\n\ntraining_args = TrainingArguments(\n    output_dir=\"./lora-finetuned\",\n    per_device_train_batch_size=2,\n    num_train_epochs=3,\n    learning_rate=2e-4,\n    logging_steps=10,\n    save_strategy=\"epoch\",\n)\n\ntrainer = Trainer(model=model, args=training_args, train_dataset=dataset)\ntrainer.train()\nmodel.save_pretrained(\"./lora-finetuned-final\")" },
      ],
      exercises: [
        {
          title: "Fine-tune a Model for Customer Support",
          description: "Create a dataset, fine-tune with LoRA, and evaluate responses",
          instructions: "Prepare instruction-formatted dataset, configure LoRA adapter with rank 16, and train the model with evaluation loss tracking.",
          starterCode: "from datasets import Dataset\nfrom transformers import pipeline\n\nsupport_data = [\n    {\"instruction\": \"Customer wants a refund\", \"response\": \"I understand. Let me process that refund for you.\"},\n    {\"instruction\": \"Product arrived damaged\", \"response\": \"I'm sorry to hear that. I'll send a replacement right away.\"},\n]\n# Format dataset, configure LoRA, train, evaluate",
          solutionCode: "from datasets import Dataset\nfrom transformers import AutoTokenizer, AutoModelForCausalLM, TrainingArguments, Trainer\nfrom peft import LoraConfig, get_peft_model, TaskType\nimport torch\n\nsupport_data = [\n    {\"instruction\": \"Customer wants a refund\", \"response\": \"I understand. Let me process that refund for you.\"},\n    {\"instruction\": \"Product arrived damaged\", \"response\": \"I'm sorry to hear that. I'll send a replacement right away.\"},\n]\n\ndef format_prompt(example):\n    return f\"### Instruction:\\n{example['instruction']}\\n\\n### Response:\\n{example['response']}\"\n\nformatted_data = [{\"text\": format_prompt(item)} for item in support_data]\ndataset = Dataset.from_list(formatted_data)\n\nlora_config = LoraConfig(\n    task_type=TaskType.CAUSAL_LM,\n    r=16,\n    lora_alpha=32,\n    lora_dropout=0.05,\n    target_modules=[\"q_proj\", \"v_proj\"],\n)\nprint(\"LoRA configuration ready with rank 16\")",
          testCases: "Dataset formatted correctly; Model fine-tuned with LoRA; Responses are helpful and polite; Handles 3+ query types",
          hints: "Use standard instruction templates (e.g. ### Instruction / ### Response) so the model learns consistent conversational boundaries.",
          difficulty: 4,
        },
      ],
      visualizations: [{ type: "flowchart", title: "Fine-tuning Pipeline", config: "{\"nodes\":[{\"id\":\"data\",\"label\":\"Collect Data\",\"x\":250,\"y\":20},{\"id\":\"format\",\"label\":\"Format Dataset\",\"x\":250,\"y\":90},{\"id\":\"lora\",\"label\":\"Apply LoRA\",\"x\":250,\"y\":160},{\"id\":\"train\",\"label\":\"Train\",\"x\":250,\"y\":230},{\"id\":\"eval\",\"label\":\"Evaluate\",\"x\":250,\"y\":300},{\"id\":\"deploy\",\"label\":\"Deploy\",\"x\":250,\"y\":370}],\"edges\":[{\"from\":\"data\",\"to\":\"format\"},{\"from\":\"format\",\"to\":\"lora\"},{\"from\":\"lora\",\"to\":\"train\"},{\"from\":\"train\",\"to\":\"eval\"},{\"from\":\"eval\",\"to\":\"deploy\"}]}" }],
      lesson: { title: "Fine-tuning and Model Customization", content: "SFT: instruction datasets, cross-entropy loss. PEFT: LoRA (low-rank adapters), QLoRA (4-bit + LoRA). RLHF: preference pairs, reward model, PPO. DPO: direct preference optimization. Practical: HuggingFace PEFT, bitsandbytes, TRL library. Dataset preparation: format, tokenize, split. Evaluation: perplexity, human eval, benchmarks.", explanation: "This lesson covers fine-tuning and customizing LLMs for specific tasks." },
    },
    {
      title: "AI Safety & Responsible AI",
      description: "Understand AI safety principles: bias detection, content filtering, jailbreak prevention, and ethical deployment.",
      slug: "ai-safety-responsible", difficulty: 3, prerequisites: [0, 1, 2],
      concepts: [
        { title: "Bias Detection & Mitigation", description: "Sources: training data, model architecture, deployment context. Detection: disparate impact ratio, equal opportunity difference. Mitigation: balanced datasets, counterfactual data augmentation, fairness constraints. Tools: IBM AI Fairness 360, Google What-If Tool." },
        { title: "Content Safety & Guardrails", description: "Input guardrails: toxicity detection, PII detection, prompt injection detection. Output guardrails: content filtering, factual accuracy check, refusal mechanisms. Moderation APIs: OpenAI Moderation, Perspective API. Custom classifiers for domain-specific safety." },
        { title: "Red Teaming & Adversarial Testing", description: "Red teaming: systematic attempt to find model failures. Attack types: prompt injection, jailbreaking, data extraction, adversarial inputs. Defenses: input sanitization, output filtering, constitutional AI. Continuous monitoring: track safety metrics in production." },
      ],
      examples: [
        { title: "Content Moderation System", description: "Build a content moderation pipeline with multiple safety checks", starterCode: "from openai import OpenAI\nimport re\n\nclient = OpenAI()\n\nclass SafetyFilter:\n    def __init__(self):\n        self.blocked_patterns = []\n    \n    def check_input(self, text):\n        pass\n    \n    def check_output(self, text):\n        pass\n    \n    def moderate(self, input_text):\n        pass", solutionCode: "from openai import OpenAI\nimport re\n\nclient = OpenAI()\n\nclass SafetyFilter:\n    def __init__(self):\n        self.blocked_patterns = [r'\\b(password|secret|token)\\s*[:=]\\s*\\S+', r'\\b(SSN|social security)\\b']\n\n    def check_input(self, text):\n        for pattern in self.blocked_patterns:\n            if re.search(pattern, text, re.IGNORECASE):\n                return False, \"Pattern blocked: personal information detected\"\n\n        response = client.moderations.create(input=text)\n        result = response.results[0]\n        if result.flagged:\n            categories = [k for k, v in result.categories.model_dump().items() if v]\n            return False, f\"Content flagged: {', '.join(categories)}\"\n        return True, \"OK\"\n\n    def check_output(self, text):\n        if len(text) > 10000:\n            return False, \"Response too long\"\n        return True, \"OK\"\n\n    def moderate(self, input_text):\n        ok, reason = self.check_input(input_text)\n        if not ok:\n            return {\"allowed\": False, \"reason\": reason}\n        return {\"allowed\": True, \"reason\": \"OK\"}\n\nfilter = SafetyFilter()\nprint(filter.moderate(\"Tell me about AI\"))\nprint(filter.moderate(\"My password is: hunter2\"))" },
      ],
      exercises: [
        {
          title: "Build a Red Team Testing Framework",
          description: "Create an automated testing system that probes an LLM for safety issues",
          instructions: "Implement RedTeamTester class that executes adversarial probes (prompt injection, PII extraction) and generates a structured safety report.",
          starterCode: "class RedTeamTester:\n    def __init__(self, model_api):\n        self.model = model_api\n        self.test_cases = []\n        self.results = []\n    \n    def add_test_case(self, prompt, expected_safe=True):\n        pass\n    \n    def run_tests(self):\n        pass\n    \n    def generate_report(self):\n        pass",
          solutionCode: "class RedTeamTester:\n    def __init__(self, model_api):\n        self.model = model_api\n        self.test_cases = []\n        self.results = []\n\n    def add_test_case(self, category, prompt, expected_refusal=True):\n        self.test_cases.append({\"category\": category, \"prompt\": prompt, \"expected_refusal\": expected_refusal})\n\n    def run_tests(self):\n        self.results = []\n        for tc in self.test_cases:\n            response = self.model(tc[\"prompt\"])\n            refused = any(w in response.lower() for w in [\"i cannot\", \"i can't\", \"sorry\", \"unable to\"])\n            passed = refused if tc[\"expected_refusal\"] else not refused\n            self.results.append({\"category\": tc[\"category\"], \"passed\": passed, \"response\": response})\n        return self.results\n\n    def generate_report(self):\n        total = len(self.results)\n        passed = sum(1 for r in self.results if r[\"passed\"])\n        return {\"total\": total, \"passed\": passed, \"pass_rate\": (passed / total) if total else 1.0}",
          testCases: "Test cases cover: prompt injection, jailbreaking, PII leakage; Results include pass/fail details; Report summarizes metrics",
          hints: "Check for standard refusal indicators like 'I cannot assist with that' when verifying safe handling of unsafe prompts.",
          difficulty: 4,
        },
      ],
      visualizations: [{ type: "flowchart", title: "AI Safety Layer Architecture", config: "{\"nodes\":[{\"id\":\"input\",\"label\":\"User Input\",\"x\":250,\"y\":20},{\"id\":\"toxicity\",\"label\":\"Toxicity Check\",\"x\":250,\"y\":90},{\"id\":\"pii\",\"label\":\"PII Detection\",\"x\":250,\"y\":160},{\"id\":\"injection\",\"label\":\"Injection Check\",\"x\":250,\"y\":230},{\"id\":\"model\",\"label\":\"LLM\",\"x\":250,\"y\":300},{\"id\":\"output\",\"label\":\"Output Filter\",\"x\":250,\"y\":370},{\"id\":\"response\",\"label\":\"Safe Response\",\"x\":250,\"y\":440}],\"edges\":[{\"from\":\"input\",\"to\":\"toxicity\"},{\"from\":\"toxicity\",\"to\":\"pii\"},{\"from\":\"pii\",\"to\":\"injection\"},{\"from\":\"injection\",\"to\":\"model\"},{\"from\":\"model\",\"to\":\"output\"},{\"from\":\"output\",\"to\":\"response\"}]}" }],
      lesson: { title: "AI Safety and Responsible AI", content: "Bias: detection (disparate impact), mitigation (balanced data, fairness constraints). Content safety: input/output guardrails, moderation APIs. Red teaming: prompt injection, jailbreaking, data extraction. Defenses: sanitization, filtering, constitutional AI. Monitoring: track safety metrics, set up alerts. Ethics: transparency, accountability, human oversight.", explanation: "This lesson covers AI safety, bias mitigation, and responsible deployment." },
    },
    {
      title: "Multimodal AI & Vision Models",
      description: "Work with multimodal models: GPT-4V, image generation, video understanding, and audio processing.",
      slug: "multimodal-ai-vision", difficulty: 4, prerequisites: [0, 1, 2],
      concepts: [
        { title: "Vision-Language Models", description: "GPT-4V, Claude 3 Vision, Gemini Pro Vision. Image understanding: describe, analyze, extract text (OCR). Input: base64 image or URL. Output: structured description or answer. Use cases: document analysis, diagram explanation, visual QA." },
        { title: "Image Generation", description: "DALL-E 3, Stable Diffusion, Midjourney. Text-to-image: prompt → image. Parameters: style, quality, size. Inpainting: edit specific regions. ControlNet: precise control over generation. LoRA for style customization. Safety: content filtering, watermarking." },
        { title: "Audio & Video AI", description: "Whisper for speech-to-text. TTS: ElevenLabs, OpenAI TTS. Video: frame extraction, scene understanding. Multimodal RAG: index images and text together. CLIP embeddings for cross-modal search. Temporal understanding: action recognition." },
      ],
      examples: [
        { title: "Vision Model Analysis", description: "Using GPT-4V to analyze images and extract structured information", starterCode: "from openai import OpenAI\nimport base64\n\nclient = OpenAI()\n\ndef encode_image(path):\n    with open(path, 'rb') as f:\n        return base64.b64encode(f.read()).decode()\n\ndef analyze_image(image_path, question):\n    pass", solutionCode: "from openai import OpenAI\nimport base64\n\nclient = OpenAI()\n\ndef encode_image(path):\n    with open(path, 'rb') as f:\n        return base64.b64encode(f.read()).decode()\n\ndef analyze_image(image_path, question):\n    base64_image = encode_image(image_path)\n    response = client.chat.completions.create(\n        model=\"gpt-4o\",\n        messages=[{\n            \"role\": \"user\",\n            \"content\": [\n                {\"type\": \"text\", \"text\": question},\n                {\"type\": \"image_url\", \"image_url\": {\"url\": f\"data:image/jpeg;base64,{base64_image}\"}},\n            ],\n        }],\n        max_tokens=500,\n    )\n    return response.choices[0].message.content\n\nresult = analyze_image(\"diagram.png\", \"Explain this diagram in detail\")\nprint(result)" },
      ],
      exercises: [
        {
          title: "Build a Multimodal Document Analyzer",
          description: "Create a system that takes images/documents, extracts text, analyzes content, and answers questions",
          instructions: "Implement MultimodalAnalyzer with extract_text and analyze_document functions returning structured JSON responses.",
          starterCode: "class MultimodalAnalyzer:\n    def __init__(self):\n        self.model = \"gpt-4o\"\n    \n    def extract_text(self, image_path):\n        pass\n    \n    def analyze_document(self, image_path, query):\n        pass",
          solutionCode: "import json\n\nclass MultimodalAnalyzer:\n    def __init__(self, vision_client=None):\n        self.client = vision_client\n        self.model = \"gpt-4o\"\n\n    def analyze_document(self, image_base64, query):\n        prompt = f\"Analyze this document image and answer the following query: {query}. Return JSON with 'summary' and 'key_findings'.\"\n        if not self.client:\n            return {\"summary\": f\"Simulated analysis for: {query}\", \"key_findings\": [\"Item 1\", \"Item 2\"]}\n        response = self.client.chat.completions.create(\n            model=self.model,\n            messages=[{\n                \"role\": \"user\",\n                \"content\": [\n                    {\"type\": \"text\", \"text\": prompt},\n                    {\"type\": \"image_url\", \"image_url\": {\"url\": f\"data:image/jpeg;base64,{image_base64}\"}},\n                ],\n            }],\n            response_format={\"type\": \"json_object\"},\n        )\n        return json.loads(response.choices[0].message.content)",
          testCases: "Extracts text from images; Answers questions about content; Returns structured JSON dictionary",
          hints: "Use response_format={'type': 'json_object'} when prompting OpenAI vision models for structured JSON output.",
          difficulty: 4,
        },
      ],
      visualizations: [{ type: "flowchart", title: "Multimodal AI Pipeline", config: "{\"nodes\":[{\"id\":\"text\",\"label\":\"Text\",\"x\":100,\"y\":20},{\"id\":\"image\",\"label\":\"Image\",\"x\":250,\"y\":20},{\"id\":\"audio\",\"label\":\"Audio\",\"x\":400,\"y\":20},{\"id\":\"encode\",\"label\":\"Encode\",\"x\":250,\"y\":100},{\"id\":\"model\",\"label\":\"Multimodal Model\",\"x\":250,\"y\":180},{\"id\":\"output\",\"label\":\"Unified Output\",\"x\":250,\"y\":260}],\"edges\":[{\"from\":\"text\",\"to\":\"encode\"},{\"from\":\"image\",\"to\":\"encode\"},{\"from\":\"audio\",\"to\":\"encode\"},{\"from\":\"encode\",\"to\":\"model\"},{\"from\":\"model\",\"to\":\"output\"}]}" }],
      lesson: { title: "Multimodal AI and Vision Models", content: "Vision: GPT-4V, Claude 3 Vision. Image understanding: description, OCR, analysis. Generation: DALL-E 3, Stable Diffusion. Audio: Whisper STT, ElevenLabs TTS. Video: frame extraction, scene understanding. Multimodal RAG: index images+text. CLIP embeddings for cross-modal search. Practical: OpenAI Vision API, Replicate, HuggingFace.", explanation: "This lesson covers multimodal AI with vision, audio, and generation capabilities." },
    },
    {
      title: "AI System Design & Architecture",
      description: "Design scalable AI systems: orchestration, evaluation pipelines, caching strategies, and cost optimization.",
      slug: "ai-system-design", difficulty: 4, prerequisites: [0, 1, 2, 3],
      concepts: [
        { title: "AI Orchestration", description: "LangChain: chains, agents, tools, memory. LlamaIndex: data connectors, indexes, query engines. Semantic Kernel: Microsoft's AI orchestration. DSPy: programming model for LLMs. Choosing: complexity vs flexibility. State management: conversation history, session state." },
        { title: "Evaluation & Testing", description: "Evals: accuracy, relevance, hallucination, safety. Automated eval: LLM-as-judge (GPT-4 evaluates responses). Benchmarks: MMLU, HumanEval, BIG-bench. A/B testing: compare prompts, models, parameters. Regression testing: prevent prompt degradation. Tools: LangSmith, Braintrust, Promptfoo." },
        { title: "Scalability & Cost", description: "Caching: semantic cache (similar prompts → cached response). Batching: group requests for throughput. Model routing: simple → small model, complex → large model. Token optimization: prompt compression, truncation. Load balancing: multiple API keys, rate limit handling. Monitoring: Datadog, Grafana, custom dashboards." },
      ],
      examples: [
        { title: "AI Router with Model Selection", description: "Build a router that selects the right model based on query complexity", starterCode: "class AIRouter:\n    def __init__(self):\n        self.models = {\n            'fast': 'gpt-3.5-turbo',\n            'smart': 'gpt-4o',\n            'vision': 'gpt-4o',\n        }\n    \n    def classify_complexity(self, query):\n        pass\n    \n    def route(self, query, has_image=False):\n        pass", solutionCode: "from openai import OpenAI\n\nclient = OpenAI()\n\nclass AIRouter:\n    def __init__(self):\n        self.models = {'fast': 'gpt-3.5-turbo', 'smart': 'gpt-4o', 'vision': 'gpt-4o'}\n        self.complexity_keywords = ['explain', 'analyze', 'compare', 'evaluate', 'design', 'architecture']\n\n    def classify_complexity(self, query):\n        complexity_score = sum(1 for kw in self.complexity_keywords if kw in query.lower())\n        if complexity_score >= 2 or len(query) > 200:\n            return 'smart'\n        return 'fast'\n\n    def route(self, query, has_image=False):\n        if has_image:\n            return self.models['vision']\n        model_type = self.classify_complexity(query)\n        return self.models[model_type]\n\nrouter = AIRouter()\nprint(router.route(\"Hello\"))\nprint(router.route(\"Explain the architecture of transformer models and compare them with RNNs\"))\nprint(router.route(\"analyze this image\", has_image=True))" },
      ],
      exercises: [
        {
          title: "Build an AI Evaluation Pipeline",
          description: "Create an automated evaluation system that tests model outputs against ground truth",
          instructions: "Implement EvalPipeline to run test cases, calculate accuracy and relevance scores, and return a summary report.",
          starterCode: "class EvalPipeline:\n    def __init__(self, test_cases):\n        self.test_cases = test_cases\n        self.results = []\n    \n    def run_eval(self, model_fn):\n        pass\n    \n    def score_accuracy(self, predicted, expected):\n        pass\n    \n    def generate_report(self):\n        pass",
          solutionCode: "class EvalPipeline:\n    def __init__(self, test_cases):\n        self.test_cases = test_cases\n        self.results = []\n\n    def score_accuracy(self, predicted, expected):\n        pred_clean = predicted.strip().lower()\n        exp_clean = expected.strip().lower()\n        if pred_clean == exp_clean:\n            return 1.0\n        if exp_clean in pred_clean:\n            return 0.8\n        return 0.0\n\n    def run_eval(self, model_fn):\n        self.results = []\n        for tc in self.test_cases:\n            pred = model_fn(tc[\"input\"])\n            score = self.score_accuracy(pred, tc[\"expected\"])\n            self.results.append({\"input\": tc[\"input\"], \"expected\": tc[\"expected\"], \"predicted\": pred, \"score\": score})\n        return self.results\n\n    def generate_report(self):\n        if not self.results:\n            return {\"total\": 0, \"average_score\": 0.0}\n        total = len(self.results)\n        avg = sum(r[\"score\"] for r in self.results) / total\n        return {\"total\": total, \"average_score\": avg, \"passed\": sum(1 for r in self.results if r[\"score\"] >= 0.8)}",
          testCases: "Runs test cases; Measures accuracy; Reports pass/fail summary metrics",
          hints: "Use substring matching or semantic scoring to tolerate minor phrasing variations in LLM responses.",
          difficulty: 4,
        },
      ],
      visualizations: [{ type: "flowchart", title: "AI System Architecture", config: "{\"nodes\":[{\"id\":\"client\",\"label\":\"Client\",\"x\":250,\"y\":20},{\"id\":\"gateway\",\"label\":\"API Gateway\",\"x\":250,\"y\":90},{\"id\":\"router\",\"label\":\"Model Router\",\"x\":250,\"y\":160},{\"id\":\"cache\",\"label\":\"Semantic Cache\",\"x\":120,\"y\":230},{\"id\":\"small\",\"label\":\"Small Model\",\"x\":380,\"y\":230},{\"id\":\"large\",\"label\":\"Large Model\",\"x\":380,\"y\":300},{\"id\":\"guard\",\"label\":\"Output Guard\",\"x\":250,\"y\":370},{\"id\":\"monitor\",\"label\":\"Monitoring\",\"x\":250,\"y\":440}],\"edges\":[{\"from\":\"client\",\"to\":\"gateway\"},{\"from\":\"gateway\",\"to\":\"router\"},{\"from\":\"router\",\"to\":\"cache\",\"label\":\"check\"},{\"from\":\"cache\",\"to\":\"guard\",\"label\":\"hit\"},{\"from\":\"router\",\"to\":\"small\",\"label\":\"simple\"},{\"from\":\"router\",\"to\":\"large\",\"label\":\"complex\"},{\"from\":\"small\",\"to\":\"guard\"},{\"from\":\"large\",\"to\":\"guard\"},{\"from\":\"guard\",\"to\":\"monitor\"}]}" }],
      lesson: { title: "AI System Design and Architecture", content: "Orchestration: LangChain, LlamaIndex, DSPy. Evaluation: LLM-as-judge, automated evals, A/B testing. Caching: semantic cache, exact match. Routing: complexity-based model selection. Cost: token optimization, batching, load balancing. Monitoring: Datadog, Grafana, LangSmith. Architecture patterns: gateway → router → cache/LLM → guard → monitor.", explanation: "This lesson covers designing scalable AI systems and evaluation pipelines." },
    },
  ],
};
